#!/bin/sh

php="D:/appweb/xampp/php/php.exe"
proclame="D:/Git/ProclamerManifestGenerator/proclame.php"
path=$(git rev-parse --show-toplevel)
config=$path/appcache.json

echo "executing pre-commit"

#executing manifest generation
$php $proclame $path $config
output=$?
output2=0

if test $output -eq 0
	then
	manifest=$(sed -nr -e 's/"manifest":([^"]*)(")(.+)(")(,*)/\3/p' "$config")
	if test -z $manifest
		then
		manifest="manifest.appcache"
	fi
	git stage $manifest
	output2=$?
fi
echo "pre-commit finished with codes : " $output "-" $output2
exit $(($output2+$output))